import { MenuInfo } from './menu-info';

export const ROUTES: MenuInfo[] = [
  {
    path: '',
    title: 'DASHBOARD',
    icon: 'dashboard',
    class: '',
    submenu: [],
    hasClaims: [
      'DB_STATISTICS',
      'DB_BEST_SELLING_PROS',
      'DB_RECENT_SO_SHIPMENT',
      'DB_RECENT_PO_DELIVERY',
      'DB_PROD_STOCK_ALERT',
    ],
  },
  {
    path: '',
    title: 'PRODUCT',
    icon: 'widgets',
    class: 'menu-toggle',
    hasClaims: [
      'PRO_VIEW_PRODUCTS',
      'PRO_ADD_PRODUCT',
      'PRO_MANAGE_PRO_CAT',
      'PRO_MANAGE_TAX',
      'PRO_MANAGE_UNIT',
      'PRO_MANAGE_BRAND',
      'PRO_MANAGE_VARIANTS',
      'PRO_PRINT_LABELS',
      'PRO_MANAGE_DAILY_PRICES',
    ],
    submenu: [
      {
        path: 'products',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PRO_VIEW_PRODUCTS'],
      },
      {
        path: 'products/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PRO_ADD_PRODUCT'],
      },
      {
        path: 'product-category',
        title: 'PRODUCT_CATEGORY',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PRO_MANAGE_PRO_CAT'],
      },
      {
        path: 'tax',
        title: 'TAX',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PRO_MANAGE_TAX'],
      },
      {
        path: 'unitConversation',
        title: 'UNIT_CONVERSATION',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PRO_MANAGE_UNIT'],
      },
      {
        path: 'brand',
        title: 'BRAND',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PRO_MANAGE_BRAND'],
      },
      {
        path: 'variants',
        title: 'VARIANTS',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PRO_MANAGE_VARIANTS'],
      },
      {
        path: 'print-labels',
        title: 'PRINT_LABELS',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PRO_PRINT_LABELS'],
      },
      {
        path: 'daily-price-manager',
        title: 'DAILY_PRICE_MANAGER',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PRO_MANAGE_DAILY_PRICES'],
      },
    ],
  },

  {
    path: '',
    title: 'CUSTOMER',
    icon: 'people',
    class: 'menu-toggle',
    hasClaims: [
      'CUST_VIEW_CUSTOMERS',
      'CUST_ADD_CUSTOMER',
      'CUST_VIEW_CUSTOMER_LADGERS',
      'CUST_VIEW_CUSTOMER_PENDING_PAYMENTS',
    ],
    submenu: [
      {
        path: 'customer',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['CUST_VIEW_CUSTOMERS'],
      },
      {
        path: 'customer/addItem',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['CUST_ADD_CUSTOMER'],
      },
      {
        path: 'customer-sales-order',
        title: 'PENDING_PAYMENT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['CUST_VIEW_CUSTOMER_PENDING_PAYMENTS'],
      },
    ],
  },
  {
    path: '',
    title: 'SUPPLIER',
    icon: 'local_shipping',
    class: 'menu-toggle',
    hasClaims: ['SUPP_VIEW_SUPPLIERS', 'SUPP_ADD_SUPPLIER'],
    submenu: [
      {
        path: 'supplier',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SUPP_VIEW_SUPPLIERS'],
      },
      {
        path: 'supplier/manage/addItem',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SUPP_ADD_SUPPLIER'],
      },
    ],
  },
  {
    path: '',
    title: 'SALES_ORDER_REQUEST',
    icon: 'request_quote',
    class: 'menu-toggle',
    hasClaims: ['SOR_VIEW_SO_REQUESTS', 'SOR_ADD_SO_REQUEST'],
    submenu: [
      {
        path: 'sales-order-request/list',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SOR_VIEW_SO_REQUESTS'],
      },
      {
        path: 'sales-order-request/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SOR_ADD_SO_REQUEST'],
      },
    ],
  },
  {
    path: '',
    title: 'SALES_ORDER',
    icon: 'trending_up',
    class: 'menu-toggle',
    hasClaims: ['SO_VIEW_SALES_ORDERS', 'SO_ADD_SO'],
    submenu: [
      {
        path: 'sales-order/list',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SO_VIEW_SALES_ORDERS'],
      },
      {
        path: 'sales-order/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SO_ADD_SO'],
      },
      {
        path: '',
        title: 'SALES_ORDER_RETURN',
        icon: 'keyboard_return',
        class: 'ml-sub-menu',
        hasClaims: ['SO_RETURN_SO'],
        submenu: [
          {
            path: 'sales-order-return/list',
            title: 'LIST',
            icon: 'target',
            class: 'ml-menu2',
            submenu: [],
            hasClaims: ['SO_RETURN_SO'],
          },
          {
            path: 'sales-order-return/add',
            title: 'ADD_NEW',
            icon: 'target',
            class: 'ml-menu2',
            submenu: [],
            hasClaims: ['SO_RETURN_SO'],
          },
        ],
      },
    ],
  },
  {
    path: '',
    title: 'PURCHASE_ORDER',
    icon: 'shopping_cart',
    class: 'menu-toggle',
    hasClaims: ['PO_VIEW_PURCHASE_ORDERS', 'PO_ADD_PO'],
    submenu: [
      {
        path: 'purchase-order/list',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu2',
        submenu: [],
        hasClaims: ['PO_VIEW_PURCHASE_ORDERS'],
      },
      {
        path: 'purchase-order/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu2',
        submenu: [],
        hasClaims: ['PO_ADD_PO'],
      },
      {
        path: '',
        title: 'PURCHASE_ORDER_REQUEST',
        icon: 'assignment',
        class: 'ml-sub-menu',
        hasClaims: ['POR_VIEW_PO_REQUESTS', 'POR_ADD_PO_REQUEST'],
        submenu: [
          {
            path: 'purchase-order-request/list',
            title: 'LIST',
            icon: 'target',
            class: 'ml-menu2',
            submenu: [],
            hasClaims: ['POR_VIEW_PO_REQUESTS'],
          },
          {
            path: 'purchase-order-request/add',
            title: 'ADD_NEW',
            icon: 'target',
            class: 'ml-menu2',
            submenu: [],
            hasClaims: ['POR_ADD_PO_REQUEST'],
          },
        ],
      },
      {
        path: '',
        title: 'PURCHASE_ORDER_RETURN',
        icon: 'keyboard_return',
        class: 'ml-sub-menu',
        hasClaims: ['PO_RETURN_PO'],
        submenu: [
          {
            path: 'purchase-order-return/list',
            title: 'LIST',
            icon: 'target',
            class: 'ml-menu2',
            submenu: [],
            hasClaims: ['PO_RETURN_PO'],
          },
          {
            path: 'purchase-order-return/add',
            title: 'ADD_NEW',
            icon: 'target',
            class: 'ml-menu2',
            submenu: [],
            hasClaims: ['PO_RETURN_PO'],
          },
        ],
      },
    ],
  },
  {
    path: '',
    title: 'ACCOUNTING',
    icon: 'account_balance',
    class: 'menu-toggle',
    hasClaims: [
      'ACCOUNTING_VIEW_LEDGER_ACCOUNTS',
      'ACCOUNTING_VIEW_FINANCIAL_YEARS',
      'ACCOUNTING_VIEW_TRANSACTIONS',
      'ACCOUNTING_VIEW_PROFIT_LOSS_REPORT',
      'ACCOUNTING_VIEW_TAX_REPORT',
      'ACCOUNTING_VIEW_CASH_BANK_REPORT',
      'ACCOUNTING_VIEW_BALANCE_SHEET_REPORT',
      'ACCOUNTING_VIEW_ACCOUNT_BALANCE_REPORT',
      'ACCOUNTING_VIEW_GENERAL_ENTRY_REPORT',
      'ACCOUNTING_VIEW_TRIAL_BALANCE_REPORT',
      'ACCOUNTING_VIEW_CASH_FLOW_REPORT',
      'ACCOUNTING_VIEW_BOOK_CLOSE'
    ],
    submenu: [
      {
        path: 'accounting/ledger-accounts',
        title: 'LEDGER_ACCOUNTS',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_LEDGER_ACCOUNTS'],
      },
      {
        path: 'accounting/financial-year',
        title: 'FINANCIAL_YEAR',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_FINANCIAL_YEARS'],
      },

      {
        path: 'accounting/transactions',
        title: 'TRANSACTION',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_TRANSACTIONS'],
      },
      {
        path: 'accounting/account-balance-report',
        title: 'ACCOUNT_BALANCE_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_ACCOUNT_BALANCE_REPORT'],
      },
      {
        path: 'accounting/balance-sheet-report',
        title: 'BALANCE_SHEET_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_BALANCE_SHEET_REPORT'],
      },
      {
        path: 'accounting/cash-bank-report',
        title: 'CASH_BANK_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_CASH_BANK_REPORT'],
      },
      {
        path: 'accounting/cash-flow-report',
        title: 'CASH_FLOW_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_CASH_FLOW_REPORT'],
      },
      {
        path: 'accounting/general-entry-report',
        title: 'GENERAL_ENTRY_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_GENERAL_ENTRY_REPORT'],
      },
      {
        path: 'accounting/profit-loss-report',
        title: 'PROFIT_VS_LOSS_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_PROFIT_LOSS_REPORT'],
      },
      {
        path: 'accounting/tax-report',
        title: 'TAX_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_TAX_REPORT'],
      },
      {
        path: 'accounting/trial-balance-report',
        title: 'TRIAL_BALANCE_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_TRIAL_BALANCE_REPORT'],
      },
      {
        path: 'accounting/payment-report',
        title: 'PAYMENT_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_TRIAL_BALANCE_REPORT'],
      },
      {
        path: 'book-close',
        title: 'BOOK_CLOSE',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ACCOUNTING_VIEW_BOOK_CLOSE'],
      },
    ],
  },
  {
    path: '',
    title: 'PAY_ROLL',
    icon: 'payments',
    class: 'menu-toggle',
    hasClaims: ['PAY_ROLL_VIEW_PAY_ROLLS', 'PAY_ROLL_MANAGE_PAY_ROLL'],
    submenu: [
      {
        path: 'pay-roll/list',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PAY_ROLL_VIEW_PAY_ROLLS'],
      },
      {
        path: 'pay-roll/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['PAY_ROLL_MANAGE_PAY_ROLL'],
      },
    ],
  },
  {
    path: '',
    title: 'LOANS',
    icon: 'credit_score',
    class: 'menu-toggle',
    submenu: [
      {
        path: 'accounting/loans',
        title: 'LIST',
        icon: '',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['LOAN_VIEW_LOANS']
      },
      {
        path: 'accounting/loan/addItem',
        title: 'ADD_NEW',
        icon: '',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['LOAN_MANAGE_LOAN']
      },
    ],
    hasClaims: ['LOAN_VIEW_LOANS', 'LOAN_MANAGE_LOAN'],
  },
  {
    path: '',
    title: 'DAMAGE_STOCK',
    icon: 'report_problem',
    class: 'menu-toggle',
    hasClaims: ['DMG_ST_VIEW_DMG_ST', 'DMG_ST_MANAGE_DMG_ST'],
    submenu: [
      {
        path: 'damaged-stock/list',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['DMG_ST_VIEW_DMG_ST'],
      },
      {
        path: 'damaged-stock/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['DMG_ST_MANAGE_DMG_ST'],
      },
    ],
  },

  {
    path: '',
    title: 'STOCK_TRANSFER',
    icon: 'swap_horiz',
    class: 'menu-toggle',
    hasClaims: ['STTFR_VIEW_STTFR', 'STTFR_MANAGE_STTFR'],
    submenu: [
      {
        path: 'stock-transfer/list',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['STTFR_VIEW_STTFR'],
      },
      {
        path: 'stock-transfer/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['STTFR_MANAGE_STTFR'],
      },
    ],
  },
  {
    path: 'inventory',
    title: 'INVENTORY',
    icon: 'shelves',
    class: '',
    hasClaims: ['INVE_VIEW_INVENTORIES'],
    submenu: [],
  },

  {
    path: '',
    title: 'EXPENSE',
    icon: 'receipt',
    class: 'menu-toggle',
    hasClaims: ['EXP_VIEW_EXPENSES', 'EXP_ADD_EXPENSE', 'EXP_MANAGE_EXP_CATEGORY'],
    submenu: [
      {
        path: 'expense',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['EXP_VIEW_EXPENSES'],
      },
      {
        path: 'expense/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['EXP_ADD_EXPENSE'],
      },
      {
        path: 'expense-category',
        title: 'EXPENSE_CATEGORY',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['EXP_MANAGE_EXP_CATEGORY'],
      },
    ],
  },

  {
    path: '',
    title: 'REPORTS',
    icon: 'bar_chart',
    class: 'menu-toggle',
    hasClaims: [
      'REP_PO_REP',
      'REP_SO_REP',
      'REP_PO_PAYMENT_REP',
      'REP_EXPENSE_REP',
      'REP_SO_PAYMENT_REP',
      'REP_SALES_VS_PURCHASE_REP',
      'REP_PRO_PP_REP',
      'REP_PRO_SO_REPORT',
      'REP_STOCK_REPORT',
      'REP_SUP_PAYMENT_REP',
      'REP_CUST_PAYMENT_REP',
      'REP_VIEW_PRO_LOSS_REP',
      'REP_VIEW_INPUT_TAX_REP',
      'REP_VIEW_OUTPUT_TAX_REP',
      'REP_VIEW_EXPENSE_TAX_REP',
    ],
    submenu: [
      {
        path: 'purchase-order-report',
        title: 'PURCHASE_ORDER_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_PO_REP'],
      },
      {
        path: 'sales-order-report',
        title: 'SALES_ORDER_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_SO_REP'],
      },
      {
        path: 'product-purchase-report',
        title: 'PRODUCT_PURCHASE_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_PRO_PP_REP'],
      },
      {
        path: 'product-sales-report',
        title: 'PRODUCT_SALES_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_PRO_SO_REPORT'],
      },
      {
        path: 'stock-report',
        title: 'STOCK_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_STOCK_REPORT'],
      },
      {
        path: 'purchase-payment-report',
        title: 'PURCHASE_PAYMENT_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_PO_PAYMENT_REP'],
      },
      {
        path: 'sales-payment-report',
        title: 'SALES_PAYMENT_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_SO_PAYMENT_REP'],
      },
      {
        path: 'expense-report',
        title: 'EXPENSE_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_EXPENSE_REP'],
      },
      {
        path: 'profit-loss-report',
        title: 'PROFIT_VS_LOSS_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_VIEW_PRO_LOSS_REP'],
      },
      {
        path: 'sales-purchase-report',
        title: 'SALES_VS_PURCHASE',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_SALES_VS_PURCHASE_REP'],
      },
      {
        path: 'supplier-payment-report',
        title: 'SUPPLIER_PAYMENT_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_SUP_PAYMENT_REP'],
      },
      {
        path: 'customer-payment-report',
        title: 'CUSTOMER_PAYMENT_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_CUST_PAYMENT_REP'],
      },
      {
        path: 'reports/input-tax-report',
        title: 'INPUT_TAX_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_VIEW_INPUT_TAX_REP'],
      },
      {
        path: 'reports/out-tax-report',
        title: 'OUTPUT_TAX_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_VIEW_OUTPUT_TAX_REP'],
      },
      {
        path: 'reports/expense-tax-report',
        title: 'EXPENSE_TAX_REPORT',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REP_VIEW_EXPENSE_TAX_REP'],
      },
    ],
  },

  {
    path: '',
    title: 'INQUIRY',
    icon: 'help_outline',
    class: 'menu-toggle',
    hasClaims: [
      'INQ_VIEW_INQUIRIES',
      'INQ_ADD_INQUIRY',
      'INQ_MANAGE_INQ_STATUS',
      'INQ_MANAGE_INQ_SOURCE',
    ],
    submenu: [
      {
        path: 'inquiry',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['INQ_VIEW_INQUIRIES'],
      },
      {
        path: 'inquiry/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['INQ_ADD_INQUIRY'],
      },
      {
        path: 'inquiry-status',
        title: 'INQUIRY_STATUS',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['INQ_MANAGE_INQ_STATUS'],
      },
      {
        path: 'inquiry-source',
        title: 'INQUIRY_SOURCES',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['INQ_MANAGE_INQ_SOURCE'],
      },
    ],
  },

  {
    path: '',
    title: 'REMINDER',
    icon: 'notifications_none',
    class: 'menu-toggle',
    hasClaims: ['REM_VIEW_REMINDERS', 'REM_ADD_REMINDER'],
    submenu: [
      {
        path: 'reminders',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REM_VIEW_REMINDERS'],
      },
      {
        path: 'reminders/add',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['REM_ADD_REMINDER'],
      },
    ],
  },

  {
    path: '',
    title: 'ROLES',
    icon: 'supervisor_account',
    class: 'menu-toggle',
    hasClaims: ['ROLES_VIEW_ROLES', 'ROLES_ADD_ROLE'],
    submenu: [
      {
        path: 'roles',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ROLES_VIEW_ROLES'],
      },
      {
        path: 'roles/manage',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['ROLES_ADD_ROLE'],
      },
    ],
  },
  {
    path: '',
    title: 'USERS',
    icon: 'group',
    class: 'menu-toggle',
    hasClaims: ['USR_VIEW_USERS', 'USR_ADD_USER', 'USR_ASSIGN_USR_ROLES'],
    submenu: [
      {
        path: 'users',
        title: 'LIST',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['USR_VIEW_USERS'],
      },
      {
        path: 'users/manage',
        title: 'ADD_NEW',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['USR_ADD_USER'],
      },
      {
        path: 'roles/users',
        title: 'USER_ROLES',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['USR_ASSIGN_USR_ROLES'],
      },
    ],
  },
  {
    path: '',
    title: 'EMAIL',
    icon: 'email',
    class: 'menu-toggle',
    hasClaims: [
      'EMAIL_MANAGE_EMAIL_SMTP_SETTINS',
      'EMAIL_MANAGE_EMAIL_TEMPLATES',
      'EMAIL_SEND_EMAIL',
    ],
    submenu: [
      {
        path: 'email-smtp',
        title: 'SMTP_SETTINGS',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['EMAIL_MANAGE_EMAIL_SMTP_SETTINS'],
      },
      {
        path: 'emailtemplate',
        title: 'EMAIL_TEMPLATE',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['EMAIL_MANAGE_EMAIL_TEMPLATES'],
      },
      {
        path: 'send-email',
        title: 'SEND_EMAIL',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['EMAIL_SEND_EMAIL'],
      },
    ],
  },
  {
    path: '',
    title: 'SETTINGS',
    icon: 'settings',
    class: 'menu-toggle',
    hasClaims: [
      'SETT_MANAGE_LOCATIONS',
      'SETT_UPDATE_COM_PROFILE',
      'SETT_MANAGE_COUNTRY',
      'SETT_MANAGE_CITY',
      'SETT_MANAGE_LAN',
      'SETT_MANAGE_LAN',
      'SETT_MANAGE_PAGE_HELPER'
    ],
    submenu: [
      {
        path: 'locations',
        title: 'BUSINESS_LOCATIONS',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SETT_MANAGE_LOCATIONS'],
      },
      {
        path: 'company-profile',
        title: 'COMPANY_PROFILE',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SETT_UPDATE_COM_PROFILE'],
      },
      {
        path: 'languages',
        title: 'LANGUAGES',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SETT_MANAGE_LAN'],
      },
      {
        path: 'page-helper',
        title: 'PAGE_HELPER',
        icon: '',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SETT_MANAGE_PAGE_HELPER'],
      },
      {
        path: 'country',
        title: 'COUNTRY',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SETT_MANAGE_COUNTRY'],
      },
      {
        path: 'cities',
        title: 'CITY',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['SETT_MANAGE_CITY'],
      },
    ],
  },
  {
    path: '',
    title: 'LOGS',
    icon: 'receipt_long',
    class: 'menu-toggle',
    hasClaims: ['LOGS_VIEW_LOGIN_AUDITS', 'LOGS_VIEW_EMAIL_LOGS', 'LOGS_VIEW_ERROR_LOGS'],
    submenu: [
      {
        path: 'login-audit',
        title: 'LOGIN_AUDIT',
        icon: 'receipt_long',
        class: 'ml-menu',
        hasClaims: ['LOGS_VIEW_LOGIN_AUDITS'],
        submenu: [],
      },
      {
        path: 'logs',
        title: 'ERROR_LOGS',
        icon: 'target',
        class: 'ml-menu',
        hasClaims: ['LOGS_VIEW_ERROR_LOGS'],
        submenu: [],
      },
      {
        path: 'email-logs',
        title: 'EMAIL_LOGS',
        icon: 'target',
        class: 'ml-menu',
        submenu: [],
        hasClaims: ['LOGS_VIEW_EMAIL_LOGS'],
      },
    ],
  },
];
