import { TableSettingJson } from '@core/domain-classes/table-setting-json';

export const TransactionTableSettings: TableSettingJson[] = [
  {
    key: 'action',
    header: 'ACTION',
    width: 100,
    type: 'text',
    isVisible: true,
    orderNumber: 1,
    allowSort: false,
  },
  {
    key: 'transactionDate',
    header: 'TRANSACTION_DATE',
    width: 100,
    type: 'datetime',
    isVisible: true,
    orderNumber: 2,
    allowSort: true,
  },
  {
    key: 'transactionNumber',
    header: 'TRANSACTION_NUMBER',
    width: 200,
    type: 'text',
    isVisible: true,
    orderNumber: 3,
    allowSort: true,
  },
  {
    key: 'referenceNumber',
    header: 'REFERENCE_NUMBER',
    width: 200,
    type: 'text',
    isVisible: true,
    orderNumber: 3,
    allowSort: true,
  },
  {
    key: 'transactionType',
    header: 'TRANSACTION_TYPE',
    width: 150,
    type: 'text',
    isVisible: true,
    orderNumber: 4,
    allowSort: true,
  },
  {
    key: 'narration',
    header: 'NARRATION',
    width: 120,
    type: 'text',
    isVisible: true,
    orderNumber: 6,
    allowSort: true,
  },
  {
    key: 'totalAmount',
    header: 'TOTAL_AMOUNT',
    width: 120,
    type: 'currency',
    isVisible: true,
    orderNumber: 6,
    allowSort: true,
  },
  {
    key: 'branchName',
    header: 'BUSINESS_LOCATION',
    width: 120,
    type: 'text',
    isVisible: true,
    orderNumber: 6,
    allowSort: true,
  },
];
